client_id: 4m8y3ORnXafY-w
client_secret: a0d7OwXd5L_O6BPP675nt3Liv28
user_agent: mopaitai downloader
username: mopaitai
password: 896kMX#Tc
save_dir: ~/Downloads

namer_module: mynamer.py

subusingnames:
  - goddesses

following:
  - abbyellison
  - angelbabyxx
  - bdsmthrowaawwaayy
  - biflexual19
  - busxslut
  - cherubesque
  - cummie69
  - erinsometimes
  - kazeclaws
  - margo_monty
  - moo_thecow
  - piercedpetanna
  - rosaverte
  - sexxykayla
  - tessafowler
  - thicc-fil-a
  - xshowin_offx

names:
  - Beth Lilly
  - Tessa Fowler
  - Denise Milani
  - Lucia Javorcekova

