client_id: 4m8y3ORnXafY-w
client_secret: a0d7OwXd5L_O6BPP675nt3Liv28
user_agent: mopaitai downloader
username: mopaitai
password: 896kMX#Tc
save_dir: ~/Downloads
delay: 2.0

namer_module: mynamer.py

subusingnames:
  - goddesses

following:
  - abbyellison
  - angelbabyxx
  - bbflerken
  - behpour
  - biflexual19
  - burlesqueboobs
  - cherubesque
  - danielleyayalaa
  - deviant-designs
  - emilia_taylor
  - katiewithgcups
  - kazeclaws
  - justviolet
  - margo_monty
  - moo_thecow
  - naotemasbbyig
  - pandoranyxie
  - peaches_n_dream
  - piercedpetanna
  - queenlivia00
  - rosaverte
  - seekrwff
  - sexxykayla
  - sweetlemonl
  - tessafowler
  - thicc-fil-a
  - xshowin_offx
  - caylinofficial

names:
  - Beth Lilly
  - Tessa Fowler
  - Denise Milani
  - Lucia Javorcekova
  - Liya Silver
  - Anveshi Jain
  - Lady Gorbunova
